"use strict";
let isRaining = true;
isRaining = false;
let age = 22;
let height = 1.77;
const nacionality = 'Brasileira';
const names = ['Lucas', 'Gabriel'];
const technologies = ['Html', 'CSS', 'Java'];
const notas = [7, 8, 9, 10];
const list = ['Salve', false, 10];
const idadeGabriel = 22;
